services:
  ocelot:
    image: ocelot:latest
    ports:
      - 127.0.0.1:34000:34000
    depends_on:
      - mysql
    volumes:
      - ./misc/ocelot/ocelot.conf:/srv/ocelot.conf
      - ./misc/ocelot/entrypoint.sh:/srv/entrypoint.sh
    environment:
      - DEVELOPMENT=true
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password
    command:
      - bash
      - /srv/entrypoint.sh
