#! /usr/bin/env php
<?php

$remove = [];
foreach (['pcntl_fork', 'pcntl_signal', 'pcntl_signal_dispatch', 'pcntl_waitpid'] as $function) {
    if (!function_exists($function)) {
        $remove[] = $function;
    }
}
if ($remove) {
    echo "The following functions musst be removed from the `disable_functions` directive in cli/php.ini:\n";
    echo "=>  ", implode(', ', $remove), "\n";
    exit;
}

define('BORIS', 1);
$_SERVER['HTTP_USER_AGENT'] = 'boris';
$_SERVER['REMOTE_ADDR']     = '127.0.0.1';

require_once(__DIR__ . '/lib/bootstrap.php');
require_once(__DIR__ . '/vendor/d11wtq/boris/lib/autoload.php');

$b = new Boris\Boris(SITE_NAME . '> ');
$b->setInspector(new Boris\ExportInspector);

$preload = [
    'cache'       => $Cache,
    'db'          => $DB,
    'debug'       => $Debug,
    'Twig'        => $Twig,
    'bonus'       => new Gazelle\Manager\Bonus,
    'collMan'     => new Gazelle\Manager\Collage,
    'forMan'      => new Gazelle\Manager\Forum,
    'pg'          => new Gazelle\DB\Pg(GZPG_DSN),
    'privMan'     => new Gazelle\Manager\Privilege,
    'tagMan'      => new Gazelle\Manager\Tag,
    'tgMan'       => new Gazelle\Manager\TGroup,
    'torMan'      => new Gazelle\Manager\Torrent,
    'userMan'     => new Gazelle\Manager\User,
];

printf("** preloaded objects:\n** %s\n", implode(', ', array_keys($preload)));
$b->setLocal($preload);
$b->start();

/*
 * Sample usage:
 *
    ./boris
    [1] ops> $db->query('select count(*) from torrents');
    // object(mysqli_result)(
    //   'current_field' => NULL,
    //   'field_count' => NULL,
    //   'lengths' => NULL,
    //   'num_rows' => NULL,
    //   'type' => NULL
    // )
    [2] ops> $db->to_array();
    // array(
    //   0 => array(
    //     0 => '14',
    //     'count(*)' => '14'
    //   )
    // )
*/
