#! /usr/bin/env php
<?php

/* Ensure that the following functions are removed from the `disable_functions`
 * directive in cli/php.ini
 *
 *   pcntl_fork
 *   pcntl_signal
 *   pcntl_signal_dispatch
 *   pcntl_waitpid
 *
 * boris won't function unless these functions are enabled in the PHP interpreter.
 *
 * The following variables are defined:
 *
 *   $db     - database connection
 *   $cache  - memcache connection
 *   $bonus  - \Gazelle\Bonus instance
 *
 * More can be added when implemented.
 */

define('BORIS', 1);
require_once(__DIR__.'/classes/config.php');
require_once(__DIR__.'/classes/classloader.php');
require_once(__DIR__.'/classes/time.class.php');
require_once(__DIR__.'/classes/regex.php');
require_once(__DIR__.'/classes/util.php');
require_once(__DIR__.'/vendor/d11wtq/boris/lib/autoload.php');

$Cache = new \CACHE($MemcachedServers);
$DB = new \DB_MYSQL;
$Debug = new \DEBUG;
$Debug->handle_errors();

G::init($DB, $Cache);

$b = new \Boris\Boris(SITE_NAME . '> ');
$b->setLocal([
    'cache'  => $Cache,
    'db'     => $DB,
    'bonus'  => new \Gazelle\Bonus($DB, $Cache)
]);
$b->start();

/*
 * Sample usage:
 *
    vagrant@contrib-jessie:/var/www$ ./boris
    [1] ops> $db->query('select count(*) from torrents');
    // object(mysqli_result)(
    //   'current_field' => NULL,
    //   'field_count' => NULL,
    //   'lengths' => NULL,
    //   'num_rows' => NULL,
    //   'type' => NULL
    // )
    [2] ops> $db->to_array();
    // array(
    //   0 => array(
    //     0 => '14',
    //     'count(*)' => '14'
    //   )
    // )
*/
