#!/usr/bin/env bash

# This is a wrapper script around calling vendor/bin/phpcs as it will return
# 0 when no errors or warnings are found, 1 for only warnings, and 2 if any errors
# are found. We do not want to fail our CI pipeline on warnings, but still want to
# show them.
# See https://github.com/squizlabs/PHP_CodeSniffer/issues/1818#issuecomment-354420927

root=$( dirname $0 )/..

$root/vendor/bin/phpcs $@ || true
