CREATE OR REPLACE TABLE recovery (
    recovery_id integer(10) unsigned not null auto_increment,
    state enum ('PENDING', 'VALIDATED', 'CLAIMED', 'ACCEPTED', 'DENIED') not null default 'PENDING',
    admin_user_id int(10) unsigned,
    created_dt datetime not null default current_timestamp,
    updated_dt datetime not null default current_timestamp,
    token varchar(19) not null,
    username varchar(20) not null,
    ipaddr varchar(40) not null,
    passhash varchar(60) CHARACTER SET ASCII,
    email varchar(255) CHARACTER SET ASCII,
    email_clean varchar(255) CHARACTER SET ASCII,
    announce varchar(100) CHARACTER SET ASCII,
    screenshot char(40) CHARACTER SET ASCII,
    invite mediumtext,
    info mediumtext,
    log mediumtext,
    PRIMARY KEY (recovery_id),
    UNIQUE KEY (username),
    UNIQUE KEY (email_clean),
    KEY (email),
    KEY (state),
    KEY (admin_user_id)
);
